#Create a lambda deployment package with the necessary dependencies and code files.
FROM public.ecr.aws/lambda/python:3.14
# Install dependencies
COPY requirements.txt ${LAMBDA_TASK_ROOT}/
RUN pip install -r requirements.txt -t ${LAMBDA_TASK_ROOT}/
# Copy the lambda function code and other necessary files
COPY lambda_function.py ${LAMBDA_TASK_ROOT}/
COPY extract.py ${LAMBDA_TASK_ROOT}/
COPY transform_clean.py ${LAMBDA_TASK_ROOT}/
COPY vector_embedding.py ${LAMBDA_TASK_ROOT}/
COPY loading.py ${LAMBDA_TASK_ROOT}/

# Set AWS region for local development
ENV AWS_REGION=eu-west-2

# Set the CMD to your handler (could also be done as a parameter override outside of the Dockerfile)
CMD ["lambda_function.lambda_handler"]
