name: Report Issue
description: Report a new issue
title: "[ISSUE]: "
labels: ["bug"]
assignees: []
body:

  - type: textarea
    id: issue
    attributes:
      label: Issue
      description: Please be specific
      placeholder: Describe the issue here
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: What is needed for this to be complete
      placeholder: List the acceptance criteria
    validations:
      required: true