name: Report Task
description: Report a new task
title: "[TASK: ]: "
labels: ["enhancement"]
assignees: []
body:
  - type: textarea
    id: task
    attributes:
      label: Task
      description: Please be specific
      placeholder: Describe the task here
    validations:
      required: true

  - type: textarea
    id: user_story
    attributes:
      label: User Story
      description: Describe the user story
      placeholder: "As a ___, I want to be able to ___, so that I can ___"
    validations:
      required: false

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: What is needed for this to be complete
      placeholder: List the acceptance criteria
    validations:
      required: true